---
title: "abel_keya_week14_IP_Part 3_Association Rules"
output: html_notebook
---
#https://rpubs.com/Jmdhcc/mba2
#https://rstudio-pubs-static.s3.amazonaws.com/192221_2390ff48c0a64fcb9b0f6ad6b1b2b7f2.html

#http://www.socr.umich.edu/people/dinov/courses/DSPA_notes/11_Apriory_AssocRuleLearning.html
```{r}
library(plyr)
library(arulesViz)
library(RColorBrewer)
library(ggplot2)
# Load libraries
library(tidyverse) # data manipulation
library(arules) # mining association rules and frequent itemsets
#library(arulesViz) # visualization techniques for association rules
library(knitr) # dynamic report generation
library(gridExtra) # provides a number of user-level functions to work with "grid" graphics
library(lubridate) # work with dates and times

```



```{r}
# Loading our dataset
Supermarket_Sales <- read.transactions("Supermarket_Sales_Dataset II.csv", sep = ",")
summary(Supermarket_Sales)
```
```{r}
# look at the first five transactions
inspect(Supermarket_Sales[1:5])
```

```{r}
# examine the frequency of items
itemFrequency(Supermarket_Sales[, 1:3])
```

```{r}
# plot the frequency of items
itemFrequencyPlot(Supermarket_Sales, support = 0.1)
```

```{r}
itemFrequencyPlot(Supermarket_Sales, topN = 20)
```
```{r}
# a visualization of the sparse matrix for the first five transactions
image(Supermarket_Sales[1:5])
```


```{r}
# visualization of a random sample of 100 transactions
image(sample(Supermarket_Sales, 100))
```


```{r}
#Training a model on the data 
library(arules)

# default settings result in zero rules learned
apriori(Supermarket_Sales)
```


```{r}
# set better support and confidence levels to learn more rules
Supermarket_Sales_rules <- apriori(Supermarket_Sales, parameter = list(support =0.006, confidence = 0.25, minlen = 2))
```

```{r}
Supermarket_Sales_rules
```

```{r}
#Evaluating model performance 
# summary of grocery association rules
summary(Supermarket_Sales_rules)
```

```{r}
# inspect the first three rules
inspect(Supermarket_Sales_rules[1:3])
```
```{r}
# Improving model performance 

# sorting grocery rules by lift
inspect(sort(Supermarket_Sales_rules, by = "lift")[1:5])
```
```{r}
# finding subsets of rules containing any herb & pepper
herb_pepper_rules <- subset(Supermarket_Sales_rules, items %in% "herb & pepper")
inspect(herb_pepper_rules)
```
```{r}
# writing the rules to a CSV file
write(Supermarket_Sales_rules, file = "Supermarket_Sales_rules.csv",
      sep = ",", quote = TRUE, row.names = FALSE)

# converting the rule set to a data frame
Supermarket_Sales_rules_df <- as(Supermarket_Sales_rules, "data.frame")

# The rules identified by the algorithms 
str(Supermarket_Sales_rules_df)
```
```{r}
Supermarket_Sales_rules_df$rules
```

```{r}
# Verifying the object's class
# 
class(Supermarket_Sales)
```



```{r}
# Absolute Item Frequency Plot
itemFrequencyPlot(Supermarket_Sales, topN=15, type="absolute", col="wheat2",xlab="Item name", 
                  ylab="Frequency (absolute)", main="Absolute Item Frequency Plot")
```




```{r}
# Generating a summary of the transaction dataset
#  information such as the most purchased items, 
# distribution of the item sets (no. of items purchased in each transaction), 

summary(Supermarket_Sales)
```



```{r}
# Create an item frequency plot for the top 20 items
if (!require("RColorBrewer")) {
  # install color package of R
  install.packages("RColorBrewer")
  #include library RColorBrewer
  library(RColorBrewer)
}
```

```{r}
itemFrequency(Supermarket_Sales)
```

```{r}
itemFrequencyPlot(Supermarket_Sales,topN=20,type="absolute",col=brewer.pal(8,'Pastel2'), main="Absolute Item Frequency Plot")
itemFrequencyPlot(Supermarket_Sales,topN=20,type="relative",col=brewer.pal(8,'Pastel2'),main="Relative Item Frequency Plot")

```



```{r}
association.rules <- apriori(Supermarket_Sales, parameter = list(supp=0.001, conf=0.8,maxlen=10))

```


```{r}
summary(association.rules)
```


```{r}
inspect(association.rules[1:10])

```

```{r}
shorter.association.rules<- apriori(Supermarket_Sales, parameter = list(supp=0.001, conf=0.8, maxlen=3))

```


```{r}
subset.rules<- which(colSums(is.subset(association.rules, association.rules))>1)

length(subset.rules)
```


```{r}
subset.association.rules. <- association.rules[-subset.rules]

```

```{r}
bacon.association.rules <- apriori(Supermarket_Sales, parameter = list(supp=0.001, conf=0.8), appearance = list(default="lhs", rhs= "bacon"))

```

```{r}
inspect(head(bacon.association.rules))

```

```{r}
subRules <- association.rules[quality(association.rules)$confidence>0.4]

plot(subRules)
```


```{r}
plot(subRules, method = "two-key plot")

```

```{r}

plotly_arules(subRules)

```


```{r}
top10subRules <- head(subRules, n=10, by = "confidence")
plot(top10subRules, method = "graph", engine= "htmlwidget")

```

```{r}
subRules2<-head(subRules, n=20, by="lift")
plot(subRules2, method = "paracoord")
```




